/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.usemoonai.moonsdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.usemoonai.moonsdk.models.AaveReservesData

class AaveReservesDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AaveReservesData
        //val modelInstance = AaveReservesData()

        // to test the property `currentAtokenBalance`
        should("test currentAtokenBalance") {
            // uncomment below to test the property
            //modelInstance.currentAtokenBalance shouldBe ("TODO")
        }

        // to test the property `currentBorrowBalance`
        should("test currentBorrowBalance") {
            // uncomment below to test the property
            //modelInstance.currentBorrowBalance shouldBe ("TODO")
        }

        // to test the property `principalBorrowBalance`
        should("test principalBorrowBalance") {
            // uncomment below to test the property
            //modelInstance.principalBorrowBalance shouldBe ("TODO")
        }

        // to test the property `borrowRateMode`
        should("test borrowRateMode") {
            // uncomment below to test the property
            //modelInstance.borrowRateMode shouldBe ("TODO")
        }

        // to test the property `borrowRate`
        should("test borrowRate") {
            // uncomment below to test the property
            //modelInstance.borrowRate shouldBe ("TODO")
        }

        // to test the property `liquidityRate`
        should("test liquidityRate") {
            // uncomment below to test the property
            //modelInstance.liquidityRate shouldBe ("TODO")
        }

        // to test the property `originationFee`
        should("test originationFee") {
            // uncomment below to test the property
            //modelInstance.originationFee shouldBe ("TODO")
        }

        // to test the property `variableBorrowIndex`
        should("test variableBorrowIndex") {
            // uncomment below to test the property
            //modelInstance.variableBorrowIndex shouldBe ("TODO")
        }

        // to test the property `lastUpdateTimestamp`
        should("test lastUpdateTimestamp") {
            // uncomment below to test the property
            //modelInstance.lastUpdateTimestamp shouldBe ("TODO")
        }

        // to test the property `usageAsCollateralEnabled`
        should("test usageAsCollateralEnabled") {
            // uncomment below to test the property
            //modelInstance.usageAsCollateralEnabled shouldBe ("TODO")
        }

    }
}
