/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.usemoonai.moonsdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.usemoonai.moonsdk.models.AccountData

class AccountDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AccountData
        //val modelInstance = AccountData()

        // to test the property `propertyKeys`
        should("test propertyKeys") {
            // uncomment below to test the property
            //modelInstance.propertyKeys shouldBe ("TODO")
        }

        // to test the property `address`
        should("test address") {
            // uncomment below to test the property
            //modelInstance.address shouldBe ("TODO")
        }

    }
}
