/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.usemoonai.moonsdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.usemoonai.moonsdk.models.ConveyorFinanceControllerResponse
import org.usemoonai.moonsdk.models.InputBody
import org.usemoonai.moonsdk.models.Transaction
import org.usemoonai.moonsdk.models.TransactionData
import org.usemoonai.moonsdk.models.TransactionResponse
import org.usemoonai.moonsdk.models.TransactionResponseTx

class ConveyorFinanceControllerResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ConveyorFinanceControllerResponse
        //val modelInstance = ConveyorFinanceControllerResponse()

        // to test the property `success`
        should("test success") {
            // uncomment below to test the property
            //modelInstance.success shouldBe ("TODO")
        }

        // to test the property `message`
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

        // to test the property `input`
        should("test input") {
            // uncomment below to test the property
            //modelInstance.input shouldBe ("TODO")
        }

        // to test the property `convey`
        should("test convey") {
            // uncomment below to test the property
            //modelInstance.convey shouldBe ("TODO")
        }

        // to test the property ``data``
        should("test `data`") {
            // uncomment below to test the property
            //modelInstance.`data` shouldBe ("TODO")
        }

        // to test the property `tx`
        should("test tx") {
            // uncomment below to test the property
            //modelInstance.tx shouldBe ("TODO")
        }

        // to test the property `signed`
        should("test signed") {
            // uncomment below to test the property
            //modelInstance.signed shouldBe ("TODO")
        }

    }
}
