/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.usemoonai.moonsdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.usemoonai.moonsdk.models.CreateAccountInput

class CreateAccountInputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateAccountInput
        //val modelInstance = CreateAccountInput()

        // to test the property `privateKey`
        should("test privateKey") {
            // uncomment below to test the property
            //modelInstance.privateKey shouldBe ("TODO")
        }

    }
}
