/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.usemoonai.moonsdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.usemoonai.moonsdk.models.EnsResolveInput

class EnsResolveInputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EnsResolveInput
        //val modelInstance = EnsResolveInput()

        // to test the property `domain`
        should("test domain") {
            // uncomment below to test the property
            //modelInstance.domain shouldBe ("TODO")
        }

        // to test the property `chainId`
        should("test chainId") {
            // uncomment below to test the property
            //modelInstance.chainId shouldBe ("TODO")
        }

    }
}
