/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.usemoonai.moonsdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.usemoonai.moonsdk.models.GetSwapDto

class GetSwapDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetSwapDto
        //val modelInstance = GetSwapDto()

        // to test the property `src`
        should("test src") {
            // uncomment below to test the property
            //modelInstance.src shouldBe ("TODO")
        }

        // to test the property `dst`
        should("test dst") {
            // uncomment below to test the property
            //modelInstance.dst shouldBe ("TODO")
        }

        // to test the property `amount`
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `from`
        should("test from") {
            // uncomment below to test the property
            //modelInstance.from shouldBe ("TODO")
        }

        // to test the property `slippage`
        should("test slippage") {
            // uncomment below to test the property
            //modelInstance.slippage shouldBe ("TODO")
        }

        // to test the property `protocols`
        should("test protocols") {
            // uncomment below to test the property
            //modelInstance.protocols shouldBe ("TODO")
        }

        // to test the property `fee`
        should("test fee") {
            // uncomment below to test the property
            //modelInstance.fee shouldBe ("TODO")
        }

        // to test the property `disableEstimate`
        should("test disableEstimate") {
            // uncomment below to test the property
            //modelInstance.disableEstimate shouldBe ("TODO")
        }

        // to test the property `permit`
        should("test permit") {
            // uncomment below to test the property
            //modelInstance.permit shouldBe ("TODO")
        }

        // to test the property `includeTokensInfo`
        should("test includeTokensInfo") {
            // uncomment below to test the property
            //modelInstance.includeTokensInfo shouldBe ("TODO")
        }

        // to test the property `includeProtocols`
        should("test includeProtocols") {
            // uncomment below to test the property
            //modelInstance.includeProtocols shouldBe ("TODO")
        }

        // to test the property `compatibility`
        should("test compatibility") {
            // uncomment below to test the property
            //modelInstance.compatibility shouldBe ("TODO")
        }

        // to test the property `allowPartialFill`
        should("test allowPartialFill") {
            // uncomment below to test the property
            //modelInstance.allowPartialFill shouldBe ("TODO")
        }

        // to test the property `parts`
        should("test parts") {
            // uncomment below to test the property
            //modelInstance.parts shouldBe ("TODO")
        }

        // to test the property `mainRouteParts`
        should("test mainRouteParts") {
            // uncomment below to test the property
            //modelInstance.mainRouteParts shouldBe ("TODO")
        }

        // to test the property `connectorTokens`
        should("test connectorTokens") {
            // uncomment below to test the property
            //modelInstance.connectorTokens shouldBe ("TODO")
        }

        // to test the property `complexityLevel`
        should("test complexityLevel") {
            // uncomment below to test the property
            //modelInstance.complexityLevel shouldBe ("TODO")
        }

        // to test the property `gasLimit`
        should("test gasLimit") {
            // uncomment below to test the property
            //modelInstance.gasLimit shouldBe ("TODO")
        }

        // to test the property `gasPrice`
        should("test gasPrice") {
            // uncomment below to test the property
            //modelInstance.gasPrice shouldBe ("TODO")
        }

        // to test the property `referrer`
        should("test referrer") {
            // uncomment below to test the property
            //modelInstance.referrer shouldBe ("TODO")
        }

        // to test the property ``receiver``
        should("test `receiver`") {
            // uncomment below to test the property
            //modelInstance.`receiver` shouldBe ("TODO")
        }

        // to test the property `chainId`
        should("test chainId") {
            // uncomment below to test the property
            //modelInstance.chainId shouldBe ("TODO")
        }

    }
}
