/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.usemoonai.moonsdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.usemoonai.moonsdk.models.GetSupportedOnRampsResponseMessageInner
import org.usemoonai.moonsdk.models.GetSupportedOnRampsResponseMessageInnerIcons

class GetSupportedOnRampsResponseMessageInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetSupportedOnRampsResponseMessageInner
        //val modelInstance = GetSupportedOnRampsResponseMessageInner()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `displayName`
        should("test displayName") {
            // uncomment below to test the property
            //modelInstance.displayName shouldBe ("TODO")
        }

        // to test the property `icons`
        should("test icons") {
            // uncomment below to test the property
            //modelInstance.icons shouldBe ("TODO")
        }

        // to test the property `icon`
        should("test icon") {
            // uncomment below to test the property
            //modelInstance.icon shouldBe ("TODO")
        }

    }
}
