/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.usemoonai.moonsdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.usemoonai.moonsdk.models.GetSupportedOnRampsResponseMessageInnerIcons
import org.usemoonai.moonsdk.models.GetSupportedOnRampsResponseMessageInnerIconsPng

class GetSupportedOnRampsResponseMessageInnerIconsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetSupportedOnRampsResponseMessageInnerIcons
        //val modelInstance = GetSupportedOnRampsResponseMessageInnerIcons()

        // to test the property `png`
        should("test png") {
            // uncomment below to test the property
            //modelInstance.png shouldBe ("TODO")
        }

        // to test the property `svg`
        should("test svg") {
            // uncomment below to test the property
            //modelInstance.svg shouldBe ("TODO")
        }

    }
}
