/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.usemoonai.moonsdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.usemoonai.moonsdk.models.RippleInput

class RippleInputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RippleInput
        //val modelInstance = RippleInput()

        // to test the property `network`
        should("test network") {
            // uncomment below to test the property
            //modelInstance.network shouldBe ("TODO")
        }

        // to test the property `privateKey`
        should("test privateKey") {
            // uncomment below to test the property
            //modelInstance.privateKey shouldBe ("TODO")
        }

    }
}
