/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.usemoonai.moonsdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.usemoonai.moonsdk.models.SellQuote

class SellQuoteTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SellQuote
        //val modelInstance = SellQuote()

        // to test the property `recommendations`
        should("test recommendations") {
            // uncomment below to test the property
            //modelInstance.recommendations shouldBe ("TODO")
        }

        // to test the property `quoteId`
        should("test quoteId") {
            // uncomment below to test the property
            //modelInstance.quoteId shouldBe ("TODO")
        }

        // to test the property `paymentMethod`
        should("test paymentMethod") {
            // uncomment below to test the property
            //modelInstance.paymentMethod shouldBe ("TODO")
        }

        // to test the property `ramp`
        should("test ramp") {
            // uncomment below to test the property
            //modelInstance.ramp shouldBe ("TODO")
        }

        // to test the property `payout`
        should("test payout") {
            // uncomment below to test the property
            //modelInstance.payout shouldBe ("TODO")
        }

        // to test the property `transactionFee`
        should("test transactionFee") {
            // uncomment below to test the property
            //modelInstance.transactionFee shouldBe ("TODO")
        }

        // to test the property `networkFee`
        should("test networkFee") {
            // uncomment below to test the property
            //modelInstance.networkFee shouldBe ("TODO")
        }

        // to test the property `rate`
        should("test rate") {
            // uncomment below to test the property
            //modelInstance.rate shouldBe ("TODO")
        }

    }
}
