/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.usemoonai.moonsdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.usemoonai.moonsdk.models.SolanaTransactionInput

class SolanaTransactionInputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SolanaTransactionInput
        //val modelInstance = SolanaTransactionInput()

        // to test the property `to`
        should("test to") {
            // uncomment below to test the property
            //modelInstance.to shouldBe ("TODO")
        }

        // to test the property ``value``
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

        // to test the property `network`
        should("test network") {
            // uncomment below to test the property
            //modelInstance.network shouldBe ("TODO")
        }

        // to test the property `compress`
        should("test compress") {
            // uncomment below to test the property
            //modelInstance.compress shouldBe ("TODO")
        }

    }
}
