/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.usemoonai.moonsdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.usemoonai.moonsdk.models.SolanaTransactionOutput

class SolanaTransactionOutputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SolanaTransactionOutput
        //val modelInstance = SolanaTransactionOutput()

        // to test the property `signedTx`
        should("test signedTx") {
            // uncomment below to test the property
            //modelInstance.signedTx shouldBe ("TODO")
        }

        // to test the property `transactionHash`
        should("test transactionHash") {
            // uncomment below to test the property
            //modelInstance.transactionHash shouldBe ("TODO")
        }

    }
}
