/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.usemoonai.moonsdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.usemoonai.moonsdk.models.SupportedPaymentTypesMessage
import org.usemoonai.moonsdk.models.PaymentType

class SupportedPaymentTypesMessageTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SupportedPaymentTypesMessage
        //val modelInstance = SupportedPaymentTypesMessage()

        // to test the property `googlepay`
        should("test googlepay") {
            // uncomment below to test the property
            //modelInstance.googlepay shouldBe ("TODO")
        }

        // to test the property `applepay`
        should("test applepay") {
            // uncomment below to test the property
            //modelInstance.applepay shouldBe ("TODO")
        }

        // to test the property `creditcard`
        should("test creditcard") {
            // uncomment below to test the property
            //modelInstance.creditcard shouldBe ("TODO")
        }

    }
}
