/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.usemoonai.moonsdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.usemoonai.moonsdk.models.SupportedPaymentTypesCurrencyResponse
import org.usemoonai.moonsdk.models.SupportedPaymentTypesMessage

class SupportedPaymentTypesCurrencyResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SupportedPaymentTypesCurrencyResponse
        //val modelInstance = SupportedPaymentTypesCurrencyResponse()

        // to test the property `message`
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

    }
}
