/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.usemoonai.moonsdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.usemoonai.moonsdk.models.SupportedDefaultResponse
import org.usemoonai.moonsdk.models.SupportedDefaultResponseDefaults
import org.usemoonai.moonsdk.models.SupportedDefaultResponseDefaultsId

class SupportedDefaultResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SupportedDefaultResponse
        //val modelInstance = SupportedDefaultResponse()

        // to test the property `defaults`
        should("test defaults") {
            // uncomment below to test the property
            //modelInstance.defaults shouldBe ("TODO")
        }

        // to test the property `recommended`
        should("test recommended") {
            // uncomment below to test the property
            //modelInstance.recommended shouldBe ("TODO")
        }

    }
}
