/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.usemoonai.moonsdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.usemoonai.moonsdk.models.TransactionRequest

class TransactionRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TransactionRequest
        //val modelInstance = TransactionRequest()

        // to test the property `nonce`
        should("test nonce") {
            // uncomment below to test the property
            //modelInstance.nonce shouldBe ("TODO")
        }

        // to test the property ``data``
        should("test `data`") {
            // uncomment below to test the property
            //modelInstance.`data` shouldBe ("TODO")
        }

        // to test the property ``value``
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

        // to test the property `to`
        should("test to") {
            // uncomment below to test the property
            //modelInstance.to shouldBe ("TODO")
        }

        // to test the property `from`
        should("test from") {
            // uncomment below to test the property
            //modelInstance.from shouldBe ("TODO")
        }

        // to test the property `maxFeePerGas`
        should("test maxFeePerGas") {
            // uncomment below to test the property
            //modelInstance.maxFeePerGas shouldBe ("TODO")
        }

        // to test the property `maxPriorityFeePerGas`
        should("test maxPriorityFeePerGas") {
            // uncomment below to test the property
            //modelInstance.maxPriorityFeePerGas shouldBe ("TODO")
        }

    }
}
