/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.usemoonai.moonsdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.usemoonai.moonsdk.models.Transaction
import org.usemoonai.moonsdk.models.TransactionData
import org.usemoonai.moonsdk.models.TransactionRequest
import org.usemoonai.moonsdk.models.Tx

class TransactionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Transaction
        //val modelInstance = Transaction()

        // to test the property `transactionHash`
        should("test transactionHash") {
            // uncomment below to test the property
            //modelInstance.transactionHash shouldBe ("TODO")
        }

        // to test the property `signedTransaction`
        should("test signedTransaction") {
            // uncomment below to test the property
            //modelInstance.signedTransaction shouldBe ("TODO")
        }

        // to test the property `rawTransaction`
        should("test rawTransaction") {
            // uncomment below to test the property
            //modelInstance.rawTransaction shouldBe ("TODO")
        }

        // to test the property ``data``
        should("test `data`") {
            // uncomment below to test the property
            //modelInstance.`data` shouldBe ("TODO")
        }

        // to test the property `transactions`
        should("test transactions") {
            // uncomment below to test the property
            //modelInstance.transactions shouldBe ("TODO")
        }

        // to test the property `moonScanUrl`
        should("test moonScanUrl") {
            // uncomment below to test the property
            //modelInstance.moonScanUrl shouldBe ("TODO")
        }

        // to test the property `signature`
        should("test signature") {
            // uncomment below to test the property
            //modelInstance.signature shouldBe ("TODO")
        }

        // to test the property `transaction`
        should("test transaction") {
            // uncomment below to test the property
            //modelInstance.transaction shouldBe ("TODO")
        }

        // to test the property `userOps`
        should("test userOps") {
            // uncomment below to test the property
            //modelInstance.userOps shouldBe ("TODO")
        }

        // to test the property `useropTransaction`
        should("test useropTransaction") {
            // uncomment below to test the property
            //modelInstance.useropTransaction shouldBe ("TODO")
        }

    }
}
