/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.usemoonai.moonsdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.usemoonai.moonsdk.models.TransactionInputSupportedParams
import org.usemoonai.moonsdk.models.TransactionInputSupportedParamsPartnerData
import org.usemoonai.moonsdk.models.TransactionInputSupportedParamsTheme

class TransactionInputSupportedParamsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TransactionInputSupportedParams
        //val modelInstance = TransactionInputSupportedParams()

        // to test the property `partnerData`
        should("test partnerData") {
            // uncomment below to test the property
            //modelInstance.partnerData shouldBe ("TODO")
        }

        // to test the property `theme`
        should("test theme") {
            // uncomment below to test the property
            //modelInstance.theme shouldBe ("TODO")
        }

    }
}
