/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.usemoonai.moonsdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.usemoonai.moonsdk.models.TransactionResponse
import org.usemoonai.moonsdk.models.TransactionResponseInfo
import org.usemoonai.moonsdk.models.TransactionResponseTx

class TransactionResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TransactionResponse
        //val modelInstance = TransactionResponse()

        // to test the property `message`
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

        // to test the property `tx`
        should("test tx") {
            // uncomment below to test the property
            //modelInstance.tx shouldBe ("TODO")
        }

        // to test the property `info`
        should("test info") {
            // uncomment below to test the property
            //modelInstance.info shouldBe ("TODO")
        }

        // to test the property `chainId`
        should("test chainId") {
            // uncomment below to test the property
            //modelInstance.chainId shouldBe ("TODO")
        }

        // to test the property `currentBlockNumber`
        should("test currentBlockNumber") {
            // uncomment below to test the property
            //modelInstance.currentBlockNumber shouldBe ("TODO")
        }

    }
}
