/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.usemoonai.moonsdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.usemoonai.moonsdk.models.TransactionInput
import org.usemoonai.moonsdk.models.TransactionInputMetaData
import org.usemoonai.moonsdk.models.TransactionInputSupportedParams
import org.usemoonai.moonsdk.models.TransactionInputWallet

class TransactionInputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TransactionInput
        //val modelInstance = TransactionInput()

        // to test the property `supportedParams`
        should("test supportedParams") {
            // uncomment below to test the property
            //modelInstance.supportedParams shouldBe ("TODO")
        }

        // to test the property `wallet`
        should("test wallet") {
            // uncomment below to test the property
            //modelInstance.wallet shouldBe ("TODO")
        }

        // to test the property `metaData`
        should("test metaData") {
            // uncomment below to test the property
            //modelInstance.metaData shouldBe ("TODO")
        }

        // to test the property `originatingHost`
        should("test originatingHost") {
            // uncomment below to test the property
            //modelInstance.originatingHost shouldBe ("TODO")
        }

        // to test the property `partnerContext`
        should("test partnerContext") {
            // uncomment below to test the property
            //modelInstance.partnerContext shouldBe ("TODO")
        }

        // to test the property `uuid`
        should("test uuid") {
            // uncomment below to test the property
            //modelInstance.uuid shouldBe ("TODO")
        }

        // to test the property `network`
        should("test network") {
            // uncomment below to test the property
            //modelInstance.network shouldBe ("TODO")
        }

        // to test the property `paymentMethod`
        should("test paymentMethod") {
            // uncomment below to test the property
            //modelInstance.paymentMethod shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `amount`
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `destination`
        should("test destination") {
            // uncomment below to test the property
            //modelInstance.destination shouldBe ("TODO")
        }

        // to test the property `source`
        should("test source") {
            // uncomment below to test the property
            //modelInstance.source shouldBe ("TODO")
        }

        // to test the property `onramp`
        should("test onramp") {
            // uncomment below to test the property
            //modelInstance.onramp shouldBe ("TODO")
        }

    }
}
