/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.InputBody
import org.openapitools.client.models.Transaction
import org.openapitools.client.models.TransactionData
import org.openapitools.client.models.TransactionResponse
import org.openapitools.client.models.TransactionResponseTx

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param success 
 * @param message 
 * @param input 
 * @param convey 
 * @param `data` 
 * @param tx 
 * @param signed 
 */


data class ConveyorFinanceControllerResponse (

    @Json(name = "success")
    val success: kotlin.Boolean,

    @Json(name = "message")
    val message: kotlin.String,

    @Json(name = "input")
    val input: InputBody? = null,

    @Json(name = "convey")
    val convey: TransactionResponse? = null,

    @Json(name = "data")
    val `data`: TransactionData? = null,

    @Json(name = "tx")
    val tx: TransactionResponseTx? = null,

    @Json(name = "signed")
    val signed: Transaction? = null

)

