/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param abi 
 * @param bytecode 
 * @param chainId 
 * @param constructorArgs 
 */


data class DeployInput (

    @Json(name = "abi")
    val abi: kotlin.String,

    @Json(name = "bytecode")
    val bytecode: kotlin.String,

    @Json(name = "chain_id")
    val chainId: kotlin.String? = null,

    @Json(name = "constructor_args")
    val constructorArgs: kotlin.String? = null

)

