/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param `160x160` 
 * @param `32x32` 
 */


data class GetSupportedOnRampsResponseMessageInnerIconsPng (

    @Json(name = "160x160")
    val `160x160`: kotlin.String,

    @Json(name = "32x32")
    val `32x32`: kotlin.String

)

