/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.TriggerOutput

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param transactionHash 
 * @param `contract` 
 * @param logIndex 
 * @param owner 
 * @param spender 
 * @param `value` 
 * @param tokenDecimals 
 * @param tokenName 
 * @param tokenSymbol 
 * @param valueWithDecimals 
 * @param triggers 
 */


data class IERC20Approval (

    @Json(name = "transactionHash")
    val transactionHash: kotlin.String,

    @Json(name = "contract")
    val `contract`: kotlin.String,

    @Json(name = "logIndex")
    val logIndex: kotlin.String,

    @Json(name = "owner")
    val owner: kotlin.String,

    @Json(name = "spender")
    val spender: kotlin.String,

    @Json(name = "value")
    val `value`: kotlin.String,

    @Json(name = "tokenDecimals")
    val tokenDecimals: kotlin.String,

    @Json(name = "tokenName")
    val tokenName: kotlin.String,

    @Json(name = "tokenSymbol")
    val tokenSymbol: kotlin.String,

    @Json(name = "valueWithDecimals")
    val valueWithDecimals: kotlin.String? = null,

    @Json(name = "triggers")
    val triggers: kotlin.collections.List<TriggerOutput>? = null

)

