/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.TriggerOutput

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param logIndex 
 * @param transactionHash 
 * @param address 
 * @param `data` 
 * @param topic0 
 * @param topic1 
 * @param topic2 
 * @param topic3 
 * @param triggers 
 */


data class Log (

    @Json(name = "logIndex")
    val logIndex: kotlin.String,

    @Json(name = "transactionHash")
    val transactionHash: kotlin.String,

    @Json(name = "address")
    val address: kotlin.String,

    @Json(name = "data")
    val `data`: kotlin.String,

    @Json(name = "topic0")
    val topic0: kotlin.String?,

    @Json(name = "topic1")
    val topic1: kotlin.String?,

    @Json(name = "topic2")
    val topic2: kotlin.String?,

    @Json(name = "topic3")
    val topic3: kotlin.String?,

    @Json(name = "triggers")
    val triggers: kotlin.collections.List<TriggerOutput>? = null

)

