/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CryptoCurrency
import org.openapitools.client.models.FiatCurrency

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param fiat 
 * @param crypto 
 */


data class Message (

    @Json(name = "fiat")
    val fiat: kotlin.collections.List<FiatCurrency>,

    @Json(name = "crypto")
    val crypto: kotlin.collections.List<CryptoCurrency>

)

