/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.SupportedAssetResponseAssetsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param country 
 * @param assets 
 */


data class SupportedAssetResponse (

    @Json(name = "country")
    val country: kotlin.String,

    @Json(name = "assets")
    val assets: kotlin.collections.List<SupportedAssetResponseAssetsInner>

)

