/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.TransactionInputSupportedParamsPartnerDataRedirectUrl

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param redirectUrl 
 */


data class TransactionInputSupportedParamsPartnerData (

    @Json(name = "redirectUrl")
    val redirectUrl: TransactionInputSupportedParamsPartnerDataRedirectUrl

)

