/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.TransactionData
import org.openapitools.client.models.TransactionRequest
import org.openapitools.client.models.Tx

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param transactionHash 
 * @param signedTransaction 
 * @param rawTransaction 
 * @param `data` 
 * @param transactions 
 * @param moonScanUrl 
 * @param signature 
 * @param transaction 
 * @param userOps 
 * @param useropTransaction 
 */


data class Transaction (

    @Json(name = "transaction_hash")
    val transactionHash: kotlin.String? = null,

    @Json(name = "signed_transaction")
    val signedTransaction: kotlin.String? = null,

    @Json(name = "raw_transaction")
    val rawTransaction: kotlin.String? = null,

    @Json(name = "data")
    val `data`: kotlin.String? = null,

    @Json(name = "transactions")
    val transactions: kotlin.collections.List<TransactionData>? = null,

    @Json(name = "moon_scan_url")
    val moonScanUrl: kotlin.String? = null,

    @Json(name = "signature")
    val signature: kotlin.String? = null,

    @Json(name = "transaction")
    val transaction: Tx? = null,

    @Json(name = "userOps")
    val userOps: kotlin.collections.List<TransactionRequest>? = null,

    @Json(name = "userop_transaction")
    val useropTransaction: kotlin.String? = null

)

