/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.usemoonai.moonsdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param metadata 
 * @param amount 
 * @param config 
 * @param network 
 * @param currency 
 */


data class CreatePaymentIntentInput (

    @Json(name = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.String>,

    @Json(name = "amount")
    val amount: kotlin.Double,

    @Json(name = "config")
    val config: kotlin.String? = null,

    @Json(name = "network")
    val network: kotlin.String? = null,

    @Json(name = "currency")
    val currency: kotlin.String? = null

)

