/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.usemoonai.moonsdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param chainId 
 * @param `data` 
 * @param gas 
 * @param gasPrice 
 * @param gasTipCap 
 * @param gasFeeCap 
 * @param `value` 
 * @param nonce 
 * @param from 
 * @param to 
 * @param blobGas 
 * @param blobGasFeeCap 
 * @param blobHashes 
 * @param v 
 * @param r 
 * @param s 
 * @param name 
 * @param symbol 
 * @param decimals 
 * @param totalSupply 
 * @param contractAddress 
 * @param balanceOf 
 * @param allowance 
 */


data class Erc20Response (

    @Json(name = "type")
    val type: kotlin.Double? = null,

    @Json(name = "chain_id")
    val chainId: kotlin.Double? = null,

    @Json(name = "data")
    val `data`: kotlin.String? = null,

    @Json(name = "gas")
    val gas: kotlin.String? = null,

    @Json(name = "gas_price")
    val gasPrice: kotlin.String? = null,

    @Json(name = "gas_tip_cap")
    val gasTipCap: kotlin.String? = null,

    @Json(name = "gas_fee_cap")
    val gasFeeCap: kotlin.String? = null,

    @Json(name = "value")
    val `value`: kotlin.String? = null,

    @Json(name = "nonce")
    val nonce: kotlin.Double? = null,

    @Json(name = "from")
    val from: kotlin.String? = null,

    @Json(name = "to")
    val to: kotlin.String? = null,

    @Json(name = "blob_gas")
    val blobGas: kotlin.String? = null,

    @Json(name = "blob_gas_fee_cap")
    val blobGasFeeCap: kotlin.String? = null,

    @Json(name = "blob_hashes")
    val blobHashes: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "v")
    val v: kotlin.String? = null,

    @Json(name = "r")
    val r: kotlin.String? = null,

    @Json(name = "s")
    val s: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "symbol")
    val symbol: kotlin.String? = null,

    @Json(name = "decimals")
    val decimals: kotlin.String? = null,

    @Json(name = "totalSupply")
    val totalSupply: kotlin.String? = null,

    @Json(name = "contract_address")
    val contractAddress: kotlin.String? = null,

    @Json(name = "balanceOf")
    val balanceOf: kotlin.String? = null,

    @Json(name = "allowance")
    val allowance: kotlin.String? = null

)

