/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.usemoonai.moonsdk.models

import org.usemoonai.moonsdk.models.GetSupportedOnRampsResponseMessageInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param message 
 */


data class GetSupportedOnRampsResponse (

    @Json(name = "message")
    val message: kotlin.collections.List<GetSupportedOnRampsResponseMessageInner>

)

