/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.usemoonai.moonsdk.models

import org.usemoonai.moonsdk.models.TransactionInputSupportedParamsPartnerData
import org.usemoonai.moonsdk.models.TransactionInputSupportedParamsTheme

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param partnerData 
 * @param theme 
 */


data class TransactionInputSupportedParams (

    @Json(name = "partnerData")
    val partnerData: TransactionInputSupportedParamsPartnerData,

    @Json(name = "theme")
    val theme: TransactionInputSupportedParamsTheme

)

