/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.usemoonai.moonsdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param nonce 
 * @param `data` 
 * @param `value` 
 * @param to 
 * @param from 
 * @param maxFeePerGas 
 * @param maxPriorityFeePerGas 
 */


data class TransactionRequest (

    @Json(name = "nonce")
    val nonce: kotlin.String? = null,

    @Json(name = "data")
    val `data`: kotlin.String? = null,

    @Json(name = "value")
    val `value`: kotlin.String? = null,

    @Json(name = "to")
    val to: kotlin.String? = null,

    @Json(name = "from")
    val from: kotlin.String? = null,

    @Json(name = "maxFeePerGas")
    val maxFeePerGas: kotlin.String? = null,

    @Json(name = "maxPriorityFeePerGas")
    val maxPriorityFeePerGas: kotlin.String? = null

)

