/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.usemoonai.moonsdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.usemoonai.moonsdk.apis.ConveyorFinanceApi
import org.usemoonai.moonsdk.models.ConveyorFinanceControllerResponse
import org.usemoonai.moonsdk.models.TokenSwapParams

class ConveyorFinanceApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ConveyorFinanceApi
        //val apiInstance = ConveyorFinanceApi()

        // to test swap
        should("test swap") {
            // uncomment below to test swap
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //val name : kotlin.String = name_example // kotlin.String | 
            //val tokenSwapParams : TokenSwapParams =  // TokenSwapParams | 
            //val result : ConveyorFinanceControllerResponse = apiInstance.swap(authorization, name, tokenSwapParams)
            //result shouldBe ("TODO")
        }

    }
}
