/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.usemoonai.moonsdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.usemoonai.moonsdk.apis.DogeCoinApi
import org.usemoonai.moonsdk.models.AccountAPIResponse
import org.usemoonai.moonsdk.models.DogeCoinAPIResponse
import org.usemoonai.moonsdk.models.DogeCoinInput
import org.usemoonai.moonsdk.models.DogeCoinTransactionInput

class DogeCoinApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DogeCoinApi
        //val apiInstance = DogeCoinApi()

        // to test createDogeCoinAccount
        should("test createDogeCoinAccount") {
            // uncomment below to test createDogeCoinAccount
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //val dogeCoinInput : DogeCoinInput =  // DogeCoinInput | 
            //val result : AccountAPIResponse = apiInstance.createDogeCoinAccount(authorization, dogeCoinInput)
            //result shouldBe ("TODO")
        }

        // to test getDogeCoinAccount
        should("test getDogeCoinAccount") {
            // uncomment below to test getDogeCoinAccount
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //val accountName : kotlin.String = accountName_example // kotlin.String | 
            //val result : AccountAPIResponse = apiInstance.getDogeCoinAccount(authorization, accountName)
            //result shouldBe ("TODO")
        }

        // to test listDogeCoinAccounts
        should("test listDogeCoinAccounts") {
            // uncomment below to test listDogeCoinAccounts
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //val result : AccountAPIResponse = apiInstance.listDogeCoinAccounts(authorization)
            //result shouldBe ("TODO")
        }

        // to test signDogeCoinTransaction
        should("test signDogeCoinTransaction") {
            // uncomment below to test signDogeCoinTransaction
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //val accountName : kotlin.String = accountName_example // kotlin.String | 
            //val dogeCoinTransactionInput : DogeCoinTransactionInput =  // DogeCoinTransactionInput | 
            //val result : DogeCoinAPIResponse = apiInstance.signDogeCoinTransaction(authorization, accountName, dogeCoinTransactionInput)
            //result shouldBe ("TODO")
        }

    }
}
