/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.usemoonai.moonsdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.usemoonai.moonsdk.apis.ENSApi
import org.usemoonai.moonsdk.models.EnsResolveAPIResponse
import org.usemoonai.moonsdk.models.EnsResolveInput

class ENSApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ENSApi
        //val apiInstance = ENSApi()

        // to test resolve
        should("test resolve") {
            // uncomment below to test resolve
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //val ensResolveInput : EnsResolveInput =  // EnsResolveInput | 
            //val result : EnsResolveAPIResponse = apiInstance.resolve(authorization, ensResolveInput)
            //result shouldBe ("TODO")
        }

    }
}
