/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.usemoonai.moonsdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.usemoonai.moonsdk.apis.EosApi
import org.usemoonai.moonsdk.models.AccountAPIResponse
import org.usemoonai.moonsdk.models.EosAPIResponse
import org.usemoonai.moonsdk.models.EosInput
import org.usemoonai.moonsdk.models.EosTransactionInput

class EosApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EosApi
        //val apiInstance = EosApi()

        // to test createEosAccount
        should("test createEosAccount") {
            // uncomment below to test createEosAccount
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //val eosInput : EosInput =  // EosInput | 
            //val result : AccountAPIResponse = apiInstance.createEosAccount(authorization, eosInput)
            //result shouldBe ("TODO")
        }

        // to test getEosAccount
        should("test getEosAccount") {
            // uncomment below to test getEosAccount
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //val accountName : kotlin.String = accountName_example // kotlin.String | 
            //val result : AccountAPIResponse = apiInstance.getEosAccount(authorization, accountName)
            //result shouldBe ("TODO")
        }

        // to test listEosAccounts
        should("test listEosAccounts") {
            // uncomment below to test listEosAccounts
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //val result : AccountAPIResponse = apiInstance.listEosAccounts(authorization)
            //result shouldBe ("TODO")
        }

        // to test signEosTransaction
        should("test signEosTransaction") {
            // uncomment below to test signEosTransaction
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //val accountName : kotlin.String = accountName_example // kotlin.String | 
            //val eosTransactionInput : EosTransactionInput =  // EosTransactionInput | 
            //val result : EosAPIResponse = apiInstance.signEosTransaction(authorization, accountName, eosTransactionInput)
            //result shouldBe ("TODO")
        }

    }
}
