/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.usemoonai.moonsdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.usemoonai.moonsdk.apis.SolanaApi
import org.usemoonai.moonsdk.models.AccountAPIResponse
import org.usemoonai.moonsdk.models.SolanaAPIResponse
import org.usemoonai.moonsdk.models.SolanaInput
import org.usemoonai.moonsdk.models.SolanaTransactionInput

class SolanaApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SolanaApi
        //val apiInstance = SolanaApi()

        // to test createSolanaAccount
        should("test createSolanaAccount") {
            // uncomment below to test createSolanaAccount
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //val solanaInput : SolanaInput =  // SolanaInput | 
            //val result : AccountAPIResponse = apiInstance.createSolanaAccount(authorization, solanaInput)
            //result shouldBe ("TODO")
        }

        // to test getSolanaAccount
        should("test getSolanaAccount") {
            // uncomment below to test getSolanaAccount
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //val accountName : kotlin.String = accountName_example // kotlin.String | 
            //val result : AccountAPIResponse = apiInstance.getSolanaAccount(authorization, accountName)
            //result shouldBe ("TODO")
        }

        // to test listSolanaAccounts
        should("test listSolanaAccounts") {
            // uncomment below to test listSolanaAccounts
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //val result : AccountAPIResponse = apiInstance.listSolanaAccounts(authorization)
            //result shouldBe ("TODO")
        }

        // to test signSolanaTransaction
        should("test signSolanaTransaction") {
            // uncomment below to test signSolanaTransaction
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //val accountName : kotlin.String = accountName_example // kotlin.String | 
            //val solanaTransactionInput : SolanaTransactionInput =  // SolanaTransactionInput | 
            //val result : SolanaAPIResponse = apiInstance.signSolanaTransaction(authorization, accountName, solanaTransactionInput)
            //result shouldBe ("TODO")
        }

    }
}
