/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.usemoonai.moonsdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.usemoonai.moonsdk.apis.UniSwapApi
import org.usemoonai.moonsdk.models.TransactionAPIResponse
import org.usemoonai.moonsdk.models.UniswapInput

class UniSwapApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UniSwapApi
        //val apiInstance = UniSwapApi()

        // to test addLiquidity
        should("test addLiquidity") {
            // uncomment below to test addLiquidity
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //val name : kotlin.String = name_example // kotlin.String | 
            //val uniswapInput : UniswapInput =  // UniswapInput | 
            //val result : TransactionAPIResponse = apiInstance.addLiquidity(authorization, name, uniswapInput)
            //result shouldBe ("TODO")
        }

        // to test removeLiquidity
        should("test removeLiquidity") {
            // uncomment below to test removeLiquidity
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //val name : kotlin.String = name_example // kotlin.String | 
            //val uniswapInput : UniswapInput =  // UniswapInput | 
            //val result : TransactionAPIResponse = apiInstance.removeLiquidity(authorization, name, uniswapInput)
            //result shouldBe ("TODO")
        }

        // to test swapExactETHForTokens
        should("test swapExactETHForTokens") {
            // uncomment below to test swapExactETHForTokens
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //val name : kotlin.String = name_example // kotlin.String | 
            //val uniswapInput : UniswapInput =  // UniswapInput | 
            //val result : TransactionAPIResponse = apiInstance.swapExactETHForTokens(authorization, name, uniswapInput)
            //result shouldBe ("TODO")
        }

        // to test swapExactTokensForTokens
        should("test swapExactTokensForTokens") {
            // uncomment below to test swapExactTokensForTokens
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //val name : kotlin.String = name_example // kotlin.String | 
            //val uniswapInput : UniswapInput =  // UniswapInput | 
            //val result : TransactionAPIResponse = apiInstance.swapExactTokensForTokens(authorization, name, uniswapInput)
            //result shouldBe ("TODO")
        }

    }
}
