/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.usemoonai.moonsdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.usemoonai.moonsdk.apis.YearnApi
import org.usemoonai.moonsdk.models.InputBody
import org.usemoonai.moonsdk.models.TransactionAPIResponse

class YearnApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of YearnApi
        //val apiInstance = YearnApi()

        // to test addLiquidity
        should("test addLiquidity") {
            // uncomment below to test addLiquidity
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //val name : kotlin.String = name_example // kotlin.String | 
            //val inputBody : InputBody =  // InputBody | 
            //val result : TransactionAPIResponse = apiInstance.addLiquidity(authorization, name, inputBody)
            //result shouldBe ("TODO")
        }

        // to test addLiquidityWeth
        should("test addLiquidityWeth") {
            // uncomment below to test addLiquidityWeth
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //val name : kotlin.String = name_example // kotlin.String | 
            //val inputBody : InputBody =  // InputBody | 
            //val result : TransactionAPIResponse = apiInstance.addLiquidityWeth(authorization, name, inputBody)
            //result shouldBe ("TODO")
        }

        // to test removeLiquidity
        should("test removeLiquidity") {
            // uncomment below to test removeLiquidity
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //val name : kotlin.String = name_example // kotlin.String | 
            //val inputBody : InputBody =  // InputBody | 
            //val result : TransactionAPIResponse = apiInstance.removeLiquidity(authorization, name, inputBody)
            //result shouldBe ("TODO")
        }

        // to test removeLiquidityWeth
        should("test removeLiquidityWeth") {
            // uncomment below to test removeLiquidityWeth
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //val name : kotlin.String = name_example // kotlin.String | 
            //val inputBody : InputBody =  // InputBody | 
            //val result : TransactionAPIResponse = apiInstance.removeLiquidityWeth(authorization, name, inputBody)
            //result shouldBe ("TODO")
        }

    }
}
